### PR TITLE
fix: detecting `pi_content`'s end should return true

### PR DESCRIPTION
**Pull request by amaanq**

### CODE REVIEW

**Comment by amaanq** [comment]
Oops..didn't pull in latest change

**Comment by amaanq** [comment]
Well, it messed up with this:
`<?bar is ?> invalid?>`

So maybe a newline check is warranted?

**Comment by amaanq** [comment]
I added a newline check - if that isn't right let me know, I just don't really know xml that well

**Comment by ObserverOfTime** [comment]
> Well, it messed up with this:
> `<?bar is ?> invalid?>`

It's fine if it's parsed as an error in any way.

**Comment by ObserverOfTime** [comment]
> I just don't really know xml that well

Neither do I, but that seems to work.

**Pull request merged**
